### ISSUE TITLE
Error when trying to use leafsync::sync() instead of map view::sync

### ISSUE THREAD

**Issue by jamesdeweese** [r-spatial/leafsync#3]
Recently installed leafsync after getting the warning that sync() in mapview was deprecated.  After installing the package using install.packages(), I get the following error when calling leafsync::sync():

Error in copyDependencyToDir(dep, libdir, FALSE) : 
  Can't copy dependency files that don't exist: '/var/folders/n_/chy9r1gd2cn1cv4q7r52kh4c0000gn/T//RtmpxfYMRX/leaflet-providers_1.9.0.js'

**Comment by tim-salabim** [comment]
Can you please provide a reproducible example?

**Comment by jamesdeweese** [comment]
My apologies.  It was a problem with my installation.  I reinstalled and re-started the session and it works like a charm.
